name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'

    - name: Set API Key as environment variable
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: echo "API_KEY=${API_KEY}" >> $GITHUB_ENV

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
